### ISSUE TITLE
Web Hosting Provider Research

### ISSUE THREAD

**Issue by vivekmore** [vivekmore/secom#1]
Research on cost efficient web hosting providers

**Comment by adam-osman** [comment]
Option 1

SECOM is already a Silver Guidestar Participant so by signing up for a membership on grassroots.org they can get free lifetime hosting through Bluehost. Instructions for set-up are on the link below:

http://www.joomla.grassroots.org/docs/Steps-on-getting-the-FREE-Web-Hosting-New.pdf

Option 2

AWS offers nonprofits one year of free hosting. Web server must be set-up by someone with server experience.

**Comment by vivekmore** [comment]
Since BlueHost requires the hosting follow the Webpress templates we need to research other options.
The next viable candidate is Heroku.

Here is a way to host static content on Heroku:
http://www.lemiffe.com/how-to-deploy-a-static-page-to-heroku-the-easy-way/
