### ISSUE TITLE
Define the website CSS/SASS (styles / fonts / images)

### ISSUE THREAD

**Issue by vivekmore** [vivekmore/secom#3]
Define the CSS / SASS files with the [SECOM](http://www.secomministries.org/) site as a reference

**Comment by drake-p** [comment]
Fonts & colors have been added

**Comment by drake-p** [comment]
Starting work on the meal indicator

**Comment by drake-p** [comment]
Meal indicator styles are ready to go

**Comment by drake-p** [comment]
Starting to generate image artifacts for the cart items
