### ISSUE TITLE
Payment Gateway Research

### ISSUE THREAD

**Issue by vivekmore** [vivekmore/secom#5]
Identify a payment gateway that 
- is cost effective
- has integration capabilities with javascript
- has a decent customer support

**Comment by vivekmore** [comment]
PayPal API (should we choose to go with PayPal)
https://developer.paypal.com/docs/integration/web/accept-paypal-payment/#specify-payment-information-to-create-a-payment

**Comment by vivekmore** [comment]
https://demo.paypal.com/gb/navigation?merchant=beauty&page=merchantHome&device=mobile

**Comment by adam-osman** [comment]
PayPal

2.2% +.30 cents per transaction. No additional monthly or transaction fees.

**Comment by vivekmore** [comment]
Issue with passing user defined donation amount with PayPal
